# netlify.toml - Конфігурація для Netlify

[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ⬇️ Додай це для SPA (повертає index.html для будь-якого маршруту)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npx serve ."
  port = 3000
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[template.environment]
  NODE_VERSION = "18"
